import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LenisProvider from "./components/LenisProvider";
import PushOverNav from "./components/PushOverNav";
import Footer from "./components/Footer";
import { ScrollToTop } from "./components/ScrollToTop";

const ivyPrestoHeadline = localFont({
  src: "./fonts/ivy-presto-headline-light.otf",
  variable: "--font-ivy-presto-headline",
  weight: "300",
  display: "swap",
});

const neueHaasDisplay = localFont({
  src: "./fonts/NeueHaasDisplay-Roman.woff",
  variable: "--font-neue-haas-display",
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ivyPrestoHeadline.variable} ${neueHaasDisplay.variable}`}
    >
      <body className="antialiased">
        <LenisProvider>
          <PushOverNav />
          <div className="content-container bg-background text-foreground relative translate-y-0 transform">
            <ScrollToTop />
            {children}
            <Footer />
          </div>
        </LenisProvider>
      </body>
    </html>
  );
}
