import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import LenisProvider from "./components/LenisProvider";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { ScrollToTop } from "./components/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ivyPrestoHeadline = localFont({
  src: "./fonts/ivy-presto-headline-light.otf",
  variable: "--font-ivy-presto-headline",
  weight: "300",
});

const neueHaasDisplay = localFont({
  src: "./fonts/NeueHaasDisplay-Roman.woff",
  variable: "--font-neue-haas-display",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ivyPrestoHeadline.variable} ${neueHaasDisplay.variable} flex min-h-screen flex-col antialiased`}
      >
        <LenisProvider>
          <ScrollToTop />
          <Nav />
          {children}
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
